# Generated by Django 3.0.3 on 2020-02-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='organisation',
            new_name='organization',
        ),
    ]
